name: Build Check Issues

on: 
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  merge_group:
    branches:
      - master

jobs:
  auto_assign:
    name: Auto-Assign Issues
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: prabhutejad
          numOfAssignee: 1

  deploy:
    name: Deploy to Production Website
    runs-on: ubuntu-latest
    if: github.event_name == 'merge_group' || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: ./public
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
      - name: Build
        working-directory: ./public
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: DcClientApp
          path: ./public/dist
