name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - pipelines
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          name: React Code
          path: ./public/package.json
      - name: Install dependencies
          
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRSE_AA04E }}
          channelId: live
          projectId: trse-aa04e
